server:
  port: 8080
#  servlet:
#    context-path: /app #设置应用名
spring:
  application:
    name: sample-application
  profiles:
    active: ${profileActive} #正在运行的环境
  mvc:
    static-path-pattern: /**
  # html 资源缓存时间
  resources:
    cache:
      cachecontrol:
        cache-public: true
        max-age: 11100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://106.12.208.53:3306/webuy_learning?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&serverTimezone=Asia/Shanghai
    username: user01
    password: ak402507979
  jackson: #全局默认使用jackson 驼峰
#    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  redis:
#    host: 122.51.171.126
#    password: ak402507979
  thymeleaf: #html模板配置
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
  servlet: #上传文件大小配置
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/**/*.xml

logging:
  level:
    com.omen.learning.sample.client.OrderFeignClient: debug
#指标监控
management:
  server:
    port: 8081 #指定健康检查的端口
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露
  #默认先开启所有健康检查，再手动去关闭不需要开启的端点
  endpoint:
    health:
      enabled: true
      show-details: always
  #关闭某些健康检查的选项
  health:
    redis:
      enabled: false
    elasticsearch:
      enabled: false
info:
  appName: boot-admin
  version: 2.0.1
  mavenProjectName: @project.artifactId@  #使用@@可以获取maven的pom文件值
  mavenProjectVersion: @project.version@

