server:
  port: 8080
#  servlet:
#    context-path: /app #设置应用名
spring:
  application:
    name: sample-application
  profiles:
    active: ${profileActive} #正在运行的环境
  mvc:
    static-path-pattern: /**
  flyway:
    enabled: false
  #es 配置
  elasticsearch:
    rest:
      uris: 106.12.208.53:9200
      username: elastic
      password: ak402507979
  # html 资源缓存时间
  resources:
    cache:
      cachecontrol:
        cache-public: true
        max-age: 11100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://106.12.208.53:3306/webuy_learning?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&serverTimezone=Asia/Shanghai
    username: user01
    password: ak402507979
    hikari:
      connection-timeout: 50000
  jackson: #全局默认使用jackson 驼峰
#    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 122.51.171.126
    password: ak402507979
  thymeleaf: #html模板配置
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
  servlet: #上传文件大小配置
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
  #admin 监控相关配置
  boot:
    admin:
      client:
        url: http://localhost:8082
        instance:
          prefer-ip: true

mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/**/*.xml

logging:
  level:
    com.omen.learning.sample.client.OrderFeignClient: debug
#指标监控
management:
  server:
    port: 8081 #指定健康检查的端口
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露
  #默认先开启所有健康检查，再手动去关闭不需要开启的端点 展示详细信息
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    beans:
      enabled: true

  #关闭某些健康检查的选项
  health:
    redis:
      enabled: false
    elasticsearch:
      enabled: false

info:
  appName: boot-admin
  version: 2.0.1
  mavenProjectName: @project.artifactId@  #使用@@可以获取maven的pom文件值
  mavenProjectVersion: @project.version@


rocket-mq:
  name-server: 122.51.171.126:9876
  producer:
    group: TEST_SAMPLE_01_P_GROUP
    sample-provider:
      topic: TEST_SAMPLE_01
      tag: TEST_TAG
    batch-sample-provider:
      topic: TEST_SAMPLE_BATCH_01
    batch-foreach-sample-provider:
      topic: TEST_SAMPLE_BATCH_02
    sendMessageTimeout:  300000
  consumer:
    sample-consumer:
      trace: false
      customized-trace-topic: qaz
      topic: TEST_SAMPLE_01
      group: TEST_SAMPLE_01_C_GROUP
    batchSampleConsumer:
      trace: false
      topic: TEST_SAMPLE_BATCH_01
      group: TEST_SAMPLE_BATCH_01_C_GROUP
    batchForeachSampleConsumer:
      topic: TEST_SAMPLE_BATCH_02
      group: TEST_SAMPLE_BATCH_02_C_GROUP


  provider:
    sample-provider:
      topic': TEST_SAMPLE_01